DATA = {
    "COMPUTER": "A computer is an electronic device that can receive, store, process, and output data.",
    "DIGITAL COMPUTER": "This computer are capable of processing information in discrete form. In digital technology data can be in the form of letters, symbols or numbers is presented in binary form.",
    "ANALOG COMPUTER": "These computers are used to process data generated by ongoing physical processes.",
    "HYBRID COMPUTER": "These use both analog and digital. It has the speed of analog and the accuracy of digital computer. And it used as a effective means for complex simulation.",
    "SUPER COMPUTER": "These are the most powerful and expensive computers that are used for complex scientific calculations, simulations, and research.",
    "MAINFRAME COMPUTER": "These are large and powerful computers that are used by large organization such as banks, airlines, and government agencies to process huge amount of data and handle multiple users simultaneously.",
    "MINI COMPUTER": "These are smaller and less powerful than mainframe, but there are still capable of handling multiple users and processing large amounts of data.",
    "PERSONAL COMPUTER": "These are small and affordable computers that are design for individual users.",
    "WORKSTATION": "These are high-performance computers that are used by professionals.",
    "EMBEDDED COMPUTER": "These are specialized computers that are built into other devices.",
    "MOBILE DEVICES": "These are small and portable computers that are designed for on-the-go use, such as smartphones, tablets, and laptops.",
    "MICRO COMPUTER": "These are also known as Personal Computers. These type of digital computer uses microprocessor and include both dektop and laptops.",
    "RAM": "Is an electronic device, and it is faster that can match up with CPU. And it is volatile.",
    "HARD DISK": "Is an electromechinal device, and its speed is slower than RAM. And it is non-volatile.",
    "HACLER": "They will just warn you something about malicious activity going around in your computer. It wil not steal your information.",
    "CRACKER": "They will try to steal your information without informing you.",
    "SYSTEM SOFTWARE": "These are those software, without which our PC, laptop won't run.",
    "APPLICATION SOFTWARE": "These are those software, without whicgh our PC, laptop can run.",
    "VIRUS": "A malicious program that can spread through email attachments and infected websites.",
    "ABACUS": "It was invented by the chinese and it is believed to be the 1st computer. In the ABACUS, the beads are moved to some rules to perform arithmetic calculations.",
    "NAPIER'S BONES": "It is a manually operated calculating device and as the name indicates. It was also the first machine to use the decimal point system for calculation.",
    "STEPPED RECKONER": "It was developed by Gottfried Willhelm Leibniz and it was a digital mechanical calculator.",
    "ANALYTICAL ENGINE": "Another calculating machine, it was a mechanical computer that used punch cards as input.",
    "TABULATING MACHINE": "It is a mechanical tabulator that was based on punch cards. It was capable of tabulating statistics and record or sort data or information.",
    "KEYBOARD": "A common peripheral device used to input text and commands into a computer.",
    "PERIPHERAL": "These devices are used for performing the specific functions and are connected to the computer externally.",
    "MONITOR": "A device that visually displays output from a computer.",
    "BOOTING UP": "The process of starting up a computer by loading the operating system into memory.",
    "SHUTTING DOWN": "The process of shutting down a computer properly after use.",
    "CPU": "The main processing unit of a computer responsible for executing instructions."
}
a = input("ENTER THE WORD YOU WANT TO KNOW: ")
print(DATA[a])

    
